spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/diploma_dev
    username: postgres
    password: rocket146
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---
spring:
  profiles: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/diploma_prod
    username: postgres
    password: rocket146